services:
  - type: web
    name: ageiz
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: AMADEUS_CLIENT_ID
        sync: false
      - key: AMADEUS_CLIENT_SECRET
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: POE_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://ageiz.onrender.com
